# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
