# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=32)),
                ('cata', models.CharField(max_length=32)),
                ('implies', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DomainBrute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_first_domain', models.CharField(max_length=32, unique=True)),
                ('target_domain', models.CharField(max_length=32, unique=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('domain_count', models.IntegerField(default=10000)),
                ('current_index', models.IntegerField(default=0)),
                ('thread', models.IntegerField(default=4)),
                ('model', models.CharField(default='usually', max_length=16)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_domain', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=128)),
                ('ip', models.CharField(max_length=56)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=32, unique=True)),
                ('target_url', models.CharField(max_length=128, unique=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('finger_count', models.IntegerField(default=3000)),
                ('current_index', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=32)),
                ('port_num', models.IntegerField()),
                ('port_info', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ip', models.CharField(max_length=32, unique=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('port_count', models.IntegerField(default=53325)),
                ('current_index', models.IntegerField(default=0)),
                ('thread', models.IntegerField(default=4)),
                ('model', models.CharField(default='usually', max_length=16)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=32, unique=True)),
                ('target_url', models.CharField(default=None, max_length=128)),
                ('status', models.SmallIntegerField(default=0)),
                ('thread', models.IntegerField(default=4)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebExploit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.CharField(max_length=128, unique=True)),
                ('target_domain', models.CharField(max_length=32)),
                ('status', models.SmallIntegerField(default=0)),
                ('exp_count', models.IntegerField(default=10)),
                ('current_index', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebExploitResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=32)),
                ('result', models.IntegerField(default=0)),
                ('exp_type', models.CharField(max_length=32)),
                ('exp_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WebSingleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.CharField(max_length=32)),
                ('status', models.SmallIntegerField(default=0)),
                ('finger_id', models.IntegerField(default=0)),
                ('exploit_id', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
