# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('task_status', models.SmallIntegerField(default=0)),
                ('task_rate', models.IntegerField(default=0)),
                ('domain_num', models.IntegerField(default=0)),
                ('complete_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainBrute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=32)),
                ('domain_brute_status', models.SmallIntegerField(default=0)),
                ('domain_brute_rate', models.IntegerField(default=0)),
                ('domain_brute_thread', models.IntegerField(default=4)),
                ('domain_brute_result_json', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ExploitAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=32)),
                ('exploit_attack_status', models.SmallIntegerField(default=0)),
                ('exploit_attack_rate', models.IntegerField(default=0)),
                ('exploit_attack_result_json', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=32)),
                ('finger_status', models.SmallIntegerField(default=0)),
                ('finger_rate', models.IntegerField(default=0)),
                ('finger_result_json', models.CharField(max_length=256)),
                ('batch_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BatchTask')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=32)),
                ('target_ip', models.CharField(max_length=32)),
                ('port_scan_status', models.SmallIntegerField(default=0)),
                ('port_scan_rate', models.IntegerField(default=0)),
                ('port_scan_thread', models.IntegerField(default=4)),
                ('port_scan_model', models.CharField(default='usually', max_length=16)),
                ('port_scan_result_json', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SingleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('target_url', models.CharField(max_length=32)),
                ('task_status', models.SmallIntegerField(default=0)),
                ('task_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=32)),
                ('spider_status', models.SmallIntegerField(default=0)),
                ('spider_rate', models.IntegerField(default=0)),
                ('spider_thread', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='TargetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Domain')),
                ('ip', models.ManyToManyField(to='web.IpAddr')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='spider',
            name='spider_result',
            field=models.ManyToManyField(to='web.Url'),
        ),
        migrations.AddField(
            model_name='finger',
            name='single_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SingleTask'),
        ),
        migrations.AddField(
            model_name='domain',
            name='ip',
            field=models.ManyToManyField(to='web.IpAddr'),
        ),
        migrations.AddField(
            model_name='batchtask',
            name='target_domain',
            field=models.ManyToManyField(to='web.Domain'),
        ),
    ]
